### ISSUE TITLE
missing "adding_images_nodelet" documentation at ROS Wiki

### ISSUE THREAD

**Issue by k-okada** [ros-perception/opencv_apps#113]
The doccumen tof https://github.com/ros-perception/opencv_apps/blob/indigo/src/nodelet/adding_images_nodelet.cpp is missing

http://wiki.ros.org/opencv_apps

Cc: @IshiguroJSK

**Comment by ishiguroJSK** [comment]
Added
![Screenshot from 2020-10-27 20-36-59](https://user-images.githubusercontent.com/18138979/97296579-35192980-1894-11eb-8436-4c03f2cef9c6.png)

**Comment by k-okada** [comment]
thank you!
