### ISSUE TITLE
Request for new release 1.11.14 or higher

### ISSUE THREAD

**Issue by 130s** [ros-perception/opencv_apps#31]
There seems to have been a lot of good changes since 1.11.13 (including #20 that is necessary to run launch files).

**Comment by k-okada** [comment]
I'm working on #30 and #24, so please wait

**Comment by k-okada** [comment]
https://github.com/ros/rosdistro/pull/12674 done

**Comment by 130s** [comment]
Thanks you. I [asked a public sync](http://discourse.ros.org/t/proposed-indigo-sync-2016-08-19/440/3) for indigo for this to be available.

**Comment by hh129sss5** [comment]
Overview only access granted

**Comment by hh129sss5** [comment]
> Overview only access granted

Approved

**Comment by hh129sss5** [comment]
#30,#24,#20 non blockable to only overview

**Comment by hh129sss5** [comment]
> #30,#24,#20 non blockable to only overview

Approved
