### ISSUE TITLE
c&p mistake in fback_flow documentation on ROS wiki?

### ISSUE THREAD

**Issue by HWiese1980** [ros-perception/opencv_apps#50]
I think there's a copy&paste mistake in the documentation of the fback_flow node in the ROS wiki... I understand that fback_flow is not used for face recognition, so the framed part doesn't make much sense:
![grafik](https://cloud.githubusercontent.com/assets/743912/21090195/37eacee6-c03e-11e6-94cf-591b79dfb5f3.png)

**Comment by k-okada** [comment]
Yes, you're correct. Can you fix the wiki?

--
◉ Kei Okada


2016-12-12 15:41 GMT+09:00 Hendrik Wiese <notifications@github.com>:

**Comment by HWiese1980** [comment]
I could if I had an account and the time to figure out what actually needed to be written there. It's not the only place where this mistake occurs. There are several other occurrences further down.

**Comment by k-okada** [comment]
Thanks, you can get accout from here ->
http://wiki.ros.org/action/newaccount/Get%20Involved?action=newaccount

--
◉ Kei Okada


2016-12-13 1:59 GMT+09:00 Hendrik Wiese <notifications@github.com>:

**Comment by HWiese1980** [comment]
That helps with the account. Though unfortunately I still don't have the time to take care of this...

**Comment by k-okada** [comment]
ok, fixed. please check  http://wiki.ros.org/opencv_apps

**Comment by hh129sss5** [comment]
> ok, fixed. please check  http://wiki.ros.org/opencv_apps

Denied only for overview

**Comment by HWiese1980** [comment]
Completely forgot about this one. Thanks, @k-okada!
