### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by furushchev** [ros-perception/opencv_apps#70]
Since definition of some msg is changed, it should be time to release new version
CC: @k-okada

**Comment by k-okada** [comment]
done

--
◉ Kei Okada


2017-07-14 21:23 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Thank you very much!!!!!

**Comment by hh129sss5** [comment]
Granted from overview

**Comment by hh129sss5** [comment]
> Granted from overview 

Granted
