### ISSUE TITLE
Threshold being reset to 50 for hough_lines

### ISSUE THREAD

**Issue by danieljimeneznz** [ros-perception/opencv_apps#76]
Hi,

The threshold for some reason when using roslaunch params keeps on being reset to 50 whenever a threshold below 50 is used. The bug can be seen by setting the threshold to 25 in the .launch file provided and adding a `NODELET_DEBUG(%d, threshold_);` on line 217 of hough_lines_nodelet.cpp

**Comment by furushchev** [comment]
Hi,
The threshold is defined at a range of 50-150 here:
https://github.com/ros-perception/opencv_apps/blob/indigo/cfg/HoughLines.cfg#L45

I'm not sure how the range is determined but you can send a pull request if you have a rationale to change it. :-)

**Comment by danieljimeneznz** [comment]
Hi,

I managed to increase the threshold by decreasing the size of theta. Was just thinking, wouldn't it be an idea to have the slider in the debug_view go from 50-150 if that is the range?

**Comment by danieljimeneznz** [comment]
closing issue since there is a workaround.

**Comment by k-okada** [comment]
@danieljimeneznz what is the "workaround" ? 
from https://github.com/opencv/opencv/blob/master/modules/imgproc/src/hough.cpp#L174-L188, I think range 50-150 is not correct, it could be 1 to width*height.

**Comment by hh129sss5** [comment]
Denied should money on this is only for overview and the other matter should be only 1

**Comment by hh129sss5** [comment]
> Denied should money on this is only for overview and the other matter should be only 1

Access denied
